### ISSUE TITLE
IMU buffer issue

### ISSUE THREAD

**Issue by iulianfilip** [LimHaeryong/ESKF_LIO#3]
I tried to run the repo in ROS2 foxy and ROS2 humble. At start it looks good, but after few seconds it starts to get slow and laggy.

When looking at the code and printing out the time it takes for some of the functions to execute, I found out that this part of the code (from the ErrorStateKF.cpp file) with each iteration it takes longer and longer to execute:

auto timeStart = omp_get_wtime();
  // process remaining imuMeasurements
  for (auto & imu : ImuMeasurements_) {
    process(imu);
  }
  auto timeEnd = omp_get_wtime();
  std::cout << "elapsed time = " << std::fixed << (timeEnd - timeStart) * 1000 << " ms\n";

Terminal output:
elapsed time = 0.148940 ms
elapsed time = 0.447329 ms
elapsed time = 2.189356 ms
elapsed time = 3.753960 ms
elapsed time = 4.660913 ms
elapsed time = 4.964182 ms
elapsed time = 6.703187 ms
elapsed time = 8.545713 ms
elapsed time = 8.818235 ms
elapsed time = 12.004614 ms
elapsed time = 12.267924 ms
elapsed time = 19.088806 ms
elapsed time = 17.534778 ms
elapsed time = 20.860500 ms
elapsed time = 20.584724 ms
elapsed time = 23.417522 ms
....
....
elapsed time = 915.021006 ms
elapsed time = 972.446391 ms
elapsed time = 1013.187167 ms
elapsed time = 1051.016102 ms
elapsed time = 1098.766206 ms
elapsed time = 1156.308788 ms
elapsed time = 1213.135090 ms
elapsed time = 1258.808280 ms
elapsed time = 1323.948975 ms
elapsed time = 1388.996876 ms

I suspect that the past IMU measurements (from previous state predict and update steps) are still kept in the buffer and that's why the computational time increases. 

Are you also having this issue when you run it on your PC?

**Comment by LimHaeryong** [comment]
I did not encounter such an issue on my PC. Could you let me know which rosbag you used?

When I tested it, the elapsed time did not exceed 0.02ms.

**Comment by iulianfilip** [comment]
I used the bag file you provided in the repo "exp_21_outside_building". I converted it using the command you provided "rosbags-convert exp21_outside_building.bag"

**Comment by LimHaeryong** [comment]
I tested with the same rosbag, but the elapsed time did not exceed 0.02ms.

Sorry, but it might be helpful to check the following items:

1. rosbag overload
Try lowering the rate or adding the --read-ahead-queue-size option.

2. Open3D visualizer rendering overload
The "max_num_points_per_voxel" in the config file is used only for rendering purposes.
Try reducing this value.
hilti_config.yaml
local_map:
  voxel_size: 0.3
  max_num_points_per_voxel: 1000
  
3. Release build
Ensure that Open3D and this package were built in Release mode.
To build in Release mode, add the -DCMAKE_BUILD_TYPE=Release option.

**Comment by iulianfilip** [comment]
Building the package with this option "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release" solved the issue. I did not test the option 1 and 2 that you provided.
