### ISSUE TITLE
Fails with large dataset

### ISSUE THREAD

**Issue by iulianfilip** [LimHaeryong/ESKF_LIO#4]
I am trying to run my own collected dataset which is ~2km long. It starts well. The mapping is nice in the first few hundred meters, but it is getting slow when reaches the km mark. And this is after I filtered the incoming pointcloud (reduced the size in half). I also decreased the max nr. of points per voxel to 200.

Do you implement some memory management techniques in your code? (for example, discarding older frames from the current local map to decrease the processing computation requirement). If not, do you plan to do it or have an idea how to implement this?

**Comment by LimHaeryong** [comment]
The Max num points per voxel value only affects rendering, so odometry will still work even if this value is set to 0 or 1.
I am planning to add logic for removing distant map points in the near future.
